#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#


name: grub

on:
  workflow_dispatch:
    inputs:
      push: 
        description: 'push'
        default: false
        type: boolean

jobs:
  grub:
    runs-on: ubuntu-latest
    env: 
      GRUB: "grub-2.06"
      BIOS: "i386-pc i386-efi x86_64-efi"
      SIZE: "128MB 128MB"
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run : |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"

          sudo apt install -y build-essential bison flex dosfstools


      - name: Make Grub
        run : |
          GRUB="${{ env.GRUB }}"
          BIOS="${{ env.BIOS }}"

          curl -#kLO https://ftp.gnu.org/gnu/grub/${GRUB}.tar.gz
          tar zxvf ${GRUB}.tar.gz 
          pushd ${GRUB}

          for B in ${BIOS}
          do
            b=${B}
            b=(${b//-/ })
            echo "Make ${b[@]} ..."

            mkdir -p ${B}
            pushd ${B}
            ../configure --prefix=$PWD/usr -sbindir=$PWD/sbin --sysconfdir=$PWD/etc --disable-werror --target=${b[0]} --with-platform=${b[1]}
            make
            make install
            popd
          done

          popd


      - name: Make Image and Install grub
        run : |
          GRUB="${{ env.GRUB }}"
          BIOS="${{ env.BIOS }}"
          SIZE="${{ env.SIZE }}"

          # convert KB
          function convertunit() {
            v=$(echo $1 | sed 's/[^0-9]*//g')
            u=$(echo $1 | sed 's/^[0-9]*//g')

            u=$(echo $u | tr '[:lower:]' '[:upper:]')
            case $u in
                "KB") echo ${v};;
                "MB") echo $((${v} * 1024));;
                "GB") echo $((${v} * 1024 * 1024));;
                *) echo $v;;
            esac
          }

          sum=0
          idx=1
          rm -f fdisk.txt && touch fdisk.txt
          for S in ${SIZE}
          do
            s=`convertunit ${S}`
            sum=$((${sum} + ${s}))
            echo -e "n\np\n${idx}\n\n+${s}KB\n" >> fdisk.txt
            ((idx++))
          done
          echo -e "n\np\n${idx}\n\n\na\n1\nw\nq\n" >> fdisk.txt

          rm -f grub.img
          dd if=/dev/zero of=grub.img bs=1k seek=${sum} count=0 conv=sync
          fdisk grub.img < fdisk.txt
          fdisk -l grub.img

          # Install grub
          LOOPX=`sudo losetup -f`
          sudo losetup -P ${LOOPX} grub.img
          sudo mkdosfs -F32 -n RPCB1 ${LOOPX}p1
          sudo mkfs.ext2 -F -L RPCB2 ${LOOPX}p2
          for i in $(seq 3 ${idx})
          do
            sudo mkfs.ext4 -F -L RPCB${i} ${LOOPX}p${i}
          done

          sudo rm -rf RPCB1
          sudo mkdir -p RPCB1
          sudo mount ${LOOPX}p1 RPCB1

          # 由于使用 fdisk 对映像进行分区, 因此为 msdos 样式的分区表, 并使用 BIOS 引导.
          # 除了将 stage1/boot.img 放入 MBR 外, 还要将 stage1.5/core.img 嵌入到紧随其后的未分区空间中, 并且必须有空间.
          # 现在的方法是通过设备映射告诉 grub2 安装程序, 环回设置将如何映射虚拟机中的 BIOS 驱动器.
          # 例:
          # mkdir -p /mnt/boot/grub
          # cat > /mnt/boot/grub/device.map <<EOF
          # (hd0)   /dev/loop0
          # (hd0,1) /dev/loop0p1
          # EOF
          # 
          # 或者提取了已有 镜像的头对 grub.img 进行覆盖. 分去并不会破坏头数据. 
          # 提取头例: head -c 105165 redpill-xxx.img > grub.bin  # 大小 105165 通过 wc -c grub.bin 而来
          # 在分区前: dd if=grub.bin of=grub.img conv=notrunc,sync

          sudo mkdir -p RPCB1/EFI
          sudo mkdir -p RPCB1/boot/grub
          cat > device.map <<EOF
          (hd0)   ${LOOPX}
          EOF
          sudo mv device.map RPCB1/boot/grub/device.map

          for B in ${BIOS}
          do
            args=""
            args+=" ${LOOPX} --target=${B} --no-floppy --recheck --grub-mkdevicemap=RPCB1/boot/grub/device.map --boot-directory=RPCB1/boot"
            if [[ "${B}" == *"efi" ]]; then
                args+=" --efi-directory=RPCB1 --removable --no-nvram"
            else
                args+=" --root-directory=RPCB1"
            fi
            sudo ${GRUB}/${B}/grub-install ${args}
          done

          if [ -d RPCB1/boot/grub/fonts -a -f /usr/share/grub/unicode.pf2 ]; then
            sudo cp /usr/share/grub/unicode.pf2 RPCB1/boot/grub/fonts
          fi

          sudo sync

          sudo umount ${LOOPX}p1
          sudo losetup -d ${LOOPX}


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: grub
          path: |
            grub.img


      - name: Check and Push
        if: success() && inputs.push == true
        run: |
          if [ -f "grub.img" ]; then
            echo "Copy img ..."
            gzip -c grub.img > ext/boot-image-template.img.gz
          
            echo "Git push ..."
            git pull
            status=$(git status -s | grep -E 'boot-image-template.img.gz' | awk '{printf " %s", $2}')
            if [ -n "${status}" ]; then
              git add ${status}
              git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
              git push -f
            fi
          else
            echo "No change ..."
          fi
